---
title: "First Knit"
author: "Briana Barba"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended Antelope Valley Learning Academy which is an independent studies based school and I graduated in 2021. I was a lot better and found it easier in english class but struggled within math class. I did the best in my english class.    

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I currently own an Apple MacBook Air laptop. I would rate myself at a 6.5 as far as functions on the computer and being able to access material. I have good internet connection at home that allows me to access all required material. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
People tend to just call me Bri. I am fine with Bri or Briana, either one is good.   
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to obtain my dream job of working within the Federal Bureau of Investigation. I believe anything within the crimiinal justice area would benefit me in achieving my goal but I would also say psychology. I am currently trying to achieve my Associates degree in Psychology.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have visited Mexico a few times growing up and want to visit Italy in the future. I have never been in the military but if I were drafted I would choose the Marines due to my interest of being hands on in the field. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




